var utils = require("mykoop-utils");
var routes = require("./routes");
var translations = require("../locales");
var uiHooks = require("./uiHooks");
var endpoints = require("./endpoints");
var permissions = require("./permissions");
var metaDataBuilder = new utils.MetaDataBuilder();
routes.addRoutes(metaDataBuilder);
metaDataBuilder.addData("endpoints", endpoints);
metaDataBuilder.addData("translations", translations);
metaDataBuilder.addData("permissions", permissions);
metaDataBuilder.addData("uihooks", uiHooks);
module.exports = metaDataBuilder.get();
